export const START_LOADING_TEAMS = 'START_LOADING_TEAMS'
export const SUCCESSFULLY_LOADED_TEAMS = 'SUCCESSFULLY_LOADED_TEAMS'
export const SUCCESSFULLY_CREATED_TEAM = 'SUCCESSFULLY_CREATED_TEAM'
export const ERROR_CREATING_TEAM = 'ERROR_CREATING_TEAM'
export const START_LOADING_TEAM = 'START_LOADING_TEAM'


export const START_LOADING_TEAM_PLAYERS = 'START_LOADING_TEAM_PLAYERS'
export const SUCCESSFULLY_LOADED_TEAM_PLAYERS_AND_GAMES = 'SUCCESSFULLY_LOADED_TEAM_PLAYERS_AND_GAMES'
export const SUCCESSFULLY_LOADED_TEAM_PLAYERS = 'SUCCESSFULLY_LOADED_TEAM_PLAYERS'
export const SUCCESSFULLY_CREATED_PLAYER = 'SUCCESSFULLY_CREATED_PLAYER'


export const START_LOADING_GAMES = 'START_LOADING_GAMES'
export const SUCCESSFULLY_LOADED_TEAM_GAMES = 'SUCCESSFULLY_LOADED_TEAM'
export const SUCCESSFULLY_CREATED_GAME = 'SUCCESSFULLY_CREATED_GAME'

export const AUTHENTICATED = 'AUTHENTICATED'
export const NOT_AUTHENTICATED = 'NOT_AUTHENTICATED'